import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa-IR" dir='rtl'>
      <body className='font-yekan'>
        <img src="/bg.svg" alt="bg" className='absolute -z-10 h-full w-full inset-0 object-cover max-sm:hidden'/>
        {children}
        </body>
    </html>
  )
}
