import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "@/Provider/AppProvider";
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: "Teftaco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className="font-yekan">
        <AppProvider>
          <img
            src="/bg.svg"
            alt="bg"
            className="absolute -z-10 h-full w-full inset-0 object-cover max-sm:hidden"
          />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
